name: CD

on:
  schedule:
    - cron: "0 0 * * 3"
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  release:
    name: Release
    needs: [ci]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dry run
        uses: commitizen-tools/commitizen-action@0.21.0
        with:
          changelog_increment_filename: _changelog.md
          dry_run: true
          github_token: ${{ github.token }}
          no_raise: 3,21

      - name: Bump
        if: env.PREVIOUS_REVISION != env.REVISION
        uses: commitizen-tools/commitizen-action@0.21.0
        with:
          changelog_increment_filename: _changelog.md
          github_token: ${{ github.token }}
          no_raise: 3,21
