name: CI / Build

on:
  push:
    branches: [main]
    paths:
      - .github/Dockerfile
      - .github/workflows/ci-build.yml
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  build:
    name: Build
    needs: [ci]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Setup QEMU
        uses: docker/setup-qemu-action@master

      - name: Setup Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to registry
        if: github.ref_name == 'main'
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: .
          file: ./.github/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/gha-terraform-scw-icloud-domain:latest
