name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_call:
  workflow_dispatch:

env:
  TASK_X_REMOTE_TASKFILES: 1

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin" >> "$GITHUB_PATH"
          /home/linuxbrew/.linuxbrew/bin/brew install \
            actionlint \
            check-jsonschema \
            fd \
            go-task \
            jq \
            opentofu \
            prettier \
            shellcheck \
            shfmt \
            tflint \
            yamlfmt \
            yamllint \

      - name: Lint
        run: task lint --yes

  check:
    name: Check
    permissions: {}
    runs-on: ubuntu-latest
    needs: [lint]
    if: always()
    steps:
      - name: Ensure no jobs failed
        run: |-
          [ "${{ !contains(needs.*.result, 'failure') }}" = "true" ] || exit 1
